classes = ['04.05.64',
 'Akzent in Rosa',
 'Avventuroso',
 'ABC',
 'Acrobate',
 'Auf Spitzen',
 "Accès à l'été",
 'Auf Weiss II',
 'André Marfaing - Sans titre, 1963',
 'Aile de papillon',
 'Bleu III',
 'Black White',
 'Black Cross (installation)',
 'Bauhauslampe',
 'Black Square (installation)',
 'Bleu II',
 'Bild mit rotem Fleck',
 'Bleu I',
 'Bewtiful & Stwong',
 'Big Electric Chair',
 'Composition 1 t',
 'Clown',
 'Composition',
 "Chopin's Waterloo",
 'Byzantinerin (Helle Lippen)',
 'Bock syncopé n°I',
 'Chizensei Konseimao',
 'Bram van Velde - Sans Titre',
 'Chaîne de mémoire III (EG 130)',
 'Chapeau de paille_',
 'Composition A.XX',
 'Composition No. 5',
 'Composition 5 x',
 'Composition n° 522',
 'Composition 3 z',
 'Composition X',
 'Composition spatiodynamique',
 'Composition n°24',
 'Conférencier',
 'Compression',
 'Dark Blue Panel',
 'Crucifixion 12',
 'Cuadro 120',
 'Der kleine Fisch',
 'Disques de Newton. Etude pour Fugue à deux cou-leurs',
 'Dimanche',
 'Double portrait au verre de vin',
 'Cross',
 "Conte de pistils et d'étamines n°I",
 'Danse de Saint-Guy (Tabac-Rat)',
 'Explosion lyrique n°8',
 'Femme nue dans une salle de bain',
 'Femme déguisée',
 'Formes circulaires, Soleil n° 2',
 'Du jaune au violet',
 'Florentinisches Villen Viertel',
 'Femme douce',
 'Erinnerungen an die Spiegelsäle von Brüssel',
 'Explosion lyrique n° 2',
 'Figure 5',
 'Four Store Fronts Corner,',
 'Green Relief',
 'Gul kvinde ved havet',
 'Grande Composition au corbeau',
 'Grenade bleue',
 'Il Ritornante',
 'Fresh Widow',
 'Four Store Fronts Corner',
 'Frantisek Kupka',
 'Grand palimpseste jaune',
 "L'Adorable Trixie",
 "L'Addition",
 'Improvisation XIV',
 'in den Dünen',
 'In Advance of the Broken Arm',
 'Komposition (Aquarium)',
 'Inferno Hallelujah',
 'Improvisation 3',
 "L'Accusé",
 'Jeune Finlandaise',
 'La boule blanche',
 "L'Hommage au donateur",
 "La Chute d'Icare",
 'La Chambre turque',
 "L'homme qui descend",
 "L'Estaque",
 "L'Animal sorcier",
 "L'Écorché",
 "L'Apprenti ouvrier",
 "L'Homme à la charrette",
 'Le Baiser',
 'La Toilette de Cathy',
 'La Rue',
 'La Force pure III,',
 'La Seine au Pecq',
 'La Promenade',
 'La Fusée noire',
 'Lautenspielerin, 1910',
 'La Conquête de la Franche-Comté par le mois de juin',
 'La Douche',
 'Le Faubourg de Collioure',
 'Le Cirque Médrano',
 'Le Clown blessé',
 'Le Gilet de Maïakovski',
 "Le Comte St-Genois d'Anneaucourt",
 'Le Grand Ramsès',
 'Le magasin de Ben',
 'Le Cheval blanc',
 'Le marchand de journaux',
 'Le Calvaire',
 'Les arbres rouges',
 'Le Monstre de Soisy',
 'Les Boîtes',
 'Le Roman du rose n°1',
 'Le Pot à tisane',
 'Le Phare',
 'Le Songe, dit aussi Suzanne et les vieillards',
 'Les Chiffons de La Châtre - Corsets roses, printemps 1960',
 'Le Poète Philippe Soupault',
 'Le Voyageur sans boussole',
 'Liebesperlen',
 'Les Toits',
 'Les Disques dans la ville',
 'Les Quais de la Tamise',
 'Les Tours de Laon',
 'Les Mariés de la tour Eiffel',
 "Les Miroirs de l'Asie",
 'Les Ouvriers sur la charrette',
 'Les Correspondances',
 'Les Coteaux de Rueil',
 'Manège de cochons',
 'Lignes animées',
 'Maxime aux bas verts',
 'Musique',
 'Nefertari as Lautrec',
 'Léda et le cygne',
 'Meurtre n°20_1,',
 'Mao à San Marco',
 'Mit dem scharzen Bogen',
 'Michel Tapié soleil',
 'Ordonnance sur verticales en jaune',
 'Objets usuels, pour Vincent Van Gogh_',
 'Not There-Here',
 'N° 14 (Browns over Dark)',
 'Neuf Moules Mâlic',
 'O Salvador',
 'Occhio di lucertola',
 'Opus 15C',
 'Nini, danseuse aux Folies-Bergères',
 'Nu de dos',
 'Peinture 260 x 202 cm',
 'Paysan au parapluie',
 'Peinture 200 x 220 cm',
 'Peinture n° 530',
 'Peinture 131 × 162 cm',
 'Où es-tu_ Que fais-tu_,',
 'Passion',
 'Personnage',
 'Peinture, 220 × 366 cm',
 'Parade (détail)',
 'Pierre n°31 sur fond bleu',
 'Plans verticaux I',
 'Portrait de Guynemer',
 "Portrait d'Alice Derain",
 'Portrait multiple de Francis Picabia',
 'Pure Painting',
 "PR1, Portrait-relief d'Arman",
 'Portrait de Fernand Fleuret',
 'Portrait de Suzanne Duchamp',
 "Portrait d'une danseuse",
 'Relief spatiodynamique B',
 'Raumkonstruktion 3',
 'Roberte et les barres parallèles',
 'Rhythmisches',
 'Sans titre III, Kardas, vers 1925-1930',
 'Red Roofs',
 'Reciprocal Accords',
 'Relief carton',
 'Sans titre II, Kardas, vers 1925-1930',
 'Rythme',
 'Sans titre IV, Kardas, vers 1927-1929',
 'Spatiodynamique 1',
 'Sans titre, Pevsner 1923',
 'Spatiodynamique 22',
 'Sky Blue',
 'Sans titre V, Kardas, vers 1925-1930',
 'Sensation du danger',
 'Sans titre, Kardas, vers 1925-1930',
 'Sans titre, Pevsner, 1920',
 'Souffle de Mai 1968',
 'T 1956-14',
 'The Bird Walker',
 'Spatiodynamique 26 (dite _Gigogne_)',
 'Spatioplastique 6',
 'Stilleben mit zwei Tänzerinnen',
 'Spatiodynamique 8',
 'Sérénité profuse',
 'Tableau métallique - portrait à géométrie convexe',
 'The Moon',
 'Store Front',
 'Toilette - Frau vor dem Spiegel',
 'Udnie',
 'Tir',
 'Tänzerin',
 'Two Green Points',
 'Traits, plans, espace IlI',
 'Tête de turc',
 'Traits, plans et profondeur 1',
 'Totem Double face',
 'Traits noirs enroulés',
 'Unknown Journey',
 'Une Rue de Marly-le-Roi',
 'Woman with Artificial Heart',
 'Van Gogh in a landscape',
 "Vu d'ici",
 'Weihnachtsengel mit Bethlehemszene, 2. Fassung',
 "À quatre heures d'été, l'espoir",
 'Étude pour Amorpha, Fugue à deux couleurs',
 'White Over Black III',
 'Vragende Kinderen']